Add debug input hooks for improving debugging experience
blish-hud/Blish-HUD pull request #220
Opened 2020-05-13 19:35 UTC by Archomeda

A whole bunch of code to implement a separate process that gets launched that handles the global input hooks from Windows. This is currently only used on `--debug`.

No more annoying delays when debugging Blish HUD or modules, while still keeping the input hooks enabled 🎉 

If there's anything that needs to be changed, let me know.

2020-05-14 01:20 UTC, dlamkins commented
Probably going to take me a bit to get through.  Looks like there are a number of breaking changes - especially with some of the classes getting renamed.

Looks great so far, though!  🙂

2020-05-14 01:27 UTC, dlamkins commented
Would probably be good to get a quick write up of how it works at a high level.  Something that can be referenced easily later.

2020-05-23 13:20 UTC, Archomeda commented
Alright, it's been a while, and let's see if I can get everything right still.

The way it works on high level is as follows:
Depending on the launch mode, it will either use the already available one in Blish HUD, or the new debug hooks one. They are implemented through newly made interfaces so they are easily interchangeable.

The debug hooks are made in a separate project that creates a separate executable that will always live next to Blish HUD (maybe we can change that so it's included in the Blish HUD executable, but for now I've left it at this). When Blish HUD is running in this mode, it will start (and maintain) the debug hooks process. The debug hooks process will hook the global input events, just like Blish HUD normally does outside this mode. Blish HUD communicates with this process through the stdin and stdout streams.

This communication protocol is as follows:
- Blish HUD periodically sends a keep-alive message (or a ping) to keep the debug hooks process "active"
- As long as the debug hooks are active, it will intercept and forward the global input events
- Blish HUD can act on these events it receives from the debug hooks, and may send a response back
- If Blish HUD doesn't send a response back, the debug hooks will time this out shorter than the default Windows timeout to maintain responsiveness

The following configuration has been applied:
- The debug hooks process waits for 10ms before timing out a forwarded input event message and reporting back to Windows
- The debug hooks process has an internal timer that resets itself every time a ping message is received; if there's no ping for 50ms, the debug hooks process will stop the global hooks until a new ping has been received (this is to prevent timeouts due to Blish HUD being breakpointed; since the pings are sent from Blish HUD, they aren't sent when the process is paused)
- Blish HUD pings the debug hooks process every 10ms in order to be well under the 50ms timeout from above

When Blish HUD is closed, the debug hooks process will shut itself down as well:
- Either Blish HUD kills it when it's unloading
- Or the debug hooks process kills itself if it no longer detects that Blish HUD is running (its process id is sent as a command line parameter when it's started)

This is to prevent zombie processes that no one wants.

---

If there's anything more you would want to know, you know where to find me 😁

2020-05-30 01:04 UTC, dlamkins requested changes

2020-05-30 01:04 UTC, dlamkins commented on Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
> +            foreach (Keys key in passingKeys) OnKeyStateChanged(new KeyboardEventArgs(KeyboardEventType.KeyUp, key));
Is it the editor config / ReSharper config that is consolidating all of these down?

2020-05-30 01:04 UTC, dlamkins commented on Blish HUD/GameServices/Input/Mouse/MouseHandler.cs
> +            } else if (mouseEventArgs.EventType == MouseEventType.RightMouseButtonPressed) _cameraDragging = true;
I'm not a fan of skipping on braces on single liners outside of early exist / shortcircuit stuff at the top, but the mixing of having braces and not braces for some of these if blocks is a bit much.

I've kind of just stuck with https://stackoverflow.com/a/2125078/595437 to make life a bit easier.  

Was this something changed by the editorconfig or was this manually updated?

2020-05-30 01:04 UTC, dlamkins commented on Blish HUD/Blish HUD.csproj
> +    <LangVersion>8</LangVersion>
Nothing wrong with this per se, but should probably at least have a mention in the actual PR itself.

2020-05-30 10:35 UTC, Archomeda commented on Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
> +            foreach (Keys key in passingKeys) OnKeyStateChanged(new KeyboardEventArgs(KeyboardEventType.KeyUp, key));
I believe so yes. I ran ReSharper on all the files I created (maybe the ones that I have changed too).

2020-05-30 10:35 UTC, Archomeda commented on Blish HUD/GameServices/Input/Mouse/MouseHandler.cs
> +            } else if (mouseEventArgs.EventType == MouseEventType.RightMouseButtonPressed) _cameraDragging = true;
Same as the other comment. I ran ReSharper, so it must have changed this too.

2020-05-30 10:36 UTC, Archomeda commented on Blish HUD/Blish HUD.csproj
> +    <LangVersion>8</LangVersion>
Ah. You're right. I've used some statements that can only be used in version 8.

2020-06-01 21:47 UTC, dlamkins commented on Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
> +            foreach (Keys key in passingKeys) OnKeyStateChanged(new KeyboardEventArgs(KeyboardEventType.KeyUp, key));
Thanks!

2020-06-12 07:34 UTC, dlamkins approved these changes

2020-06-12 07:37 UTC, dlamkins commented
Looks like a number of breaking changes.  Will likely mark as v0.6.

2020-06-12 07:37 UTC, merged