added idea folder to gitignore
blish-hud/Blish-HUD pull request #253
Opened 2020-06-19 22:20 UTC by greaka

2020-06-24 09:54 UTC, dlamkins commented
I like this and may end up trying Rider.

After learning about the idea folder [from the support site](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-) it looks like there might be a couple of exceptions we'd want to make in there if we ever start taking advantage of some of the other Rider features.  Mind updating this with the more explicit items under the .idea folder provided [in this example .gitignore](https://github.com/JetBrains/resharper-rider-samples/blob/master/.gitignore)?

2020-06-24 09:55 UTC, dlamkins requested changes

2020-06-24 09:55 UTC, dlamkins commented on .gitignore
> +.idea/
For reference:
https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-
https://github.com/JetBrains/resharper-rider-samples/blob/master/.gitignore

2020-06-24 21:10 UTC, greaka commented
No problem, since we didn't check in any vs files so far, I opted for keeping them out of the tree

2020-06-25 07:08 UTC, dlamkins commented
Thanks!  Looks good.  Gonna give rider a try soon enough.  🙂

2020-06-25 07:09 UTC, dlamkins approved these changes

2020-06-25 07:09 UTC, merged