Gw2Mumble.IsAvailableChanged event
blish-hud/Blish-HUD pull request #333
Opened 2020-10-27 10:12 UTC by TybaIt

2020-10-27 10:38 UTC, dlamkins requested changes

2020-10-27 10:38 UTC, dlamkins commented on Blish HUD/GameServices/Gw2MumbleService.cs
> +        private bool   _prevIsAvailable               = false;
Get rid of the extra spacing here and put a newline before the `#endregion` and after the `#region Events` portions and we should be good.  👍

2020-10-27 10:38 UTC, dlamkins commented on Blish HUD/GameServices/Gw2MumbleService.cs
> +            HandleEvents();
Move this to after the other update calls in this method are made.  That way when the event is called, the fresh values are already available.

2020-10-27 15:20 UTC, greaka approved these changes

2020-10-27 23:37 UTC, TybaIt commented
Doesn't seem to fire yet. Any clue? The implementation is equal to the others.
May be just my module. But it's like two lines and breakpoints aren't hit.

2020-10-28 06:23 UTC, dlamkins commented
The Mumble Link API is technically available outside of when it is being updated. I believe `IsAvailable` is only checking to see if the memory mapped file exists to be read which could even be after the game has closed. 

Perhaps the properties on the integration service about being in game would do better for your needs since they check the time since the last tick, I believe?

2020-10-28 15:11 UTC, TybaIt commented
You mean the ``IsInGame``?

2020-10-28 15:48 UTC, TybaIt commented
ok I've removed ``Gw2Mumble.IsAvailableChanged``
in favor of ``GameIntegration.IsInGameChanged``

works well.

Not sure though why this field isn't under mumble as 
``Gw2Mumble.IsUpdating``

GameIntegration could keep the ``IsInGame`` field as an expression: 

```csharp
GameIntegration.IsInGame => Gw2Mumble.IsUpdating```

2020-11-01 16:22 UTC, dlamkins commented
It's under the `GameIntegrationService` because it has roots in other features that were added early on.

2020-11-01 16:22 UTC, dlamkins approved these changes

2020-11-01 16:28 UTC, merged