Fix for CTRL+ALT key combinations ...
blish-hud/Blish-HUD pull request #410
Opened 2021-08-04 20:14 UTC by entrhopi

and prevent some actions to trigger multiple when key is held down

2021-08-04 20:21 UTC, greaka approved these changes

2021-08-04 21:24 UTC, agaertner approved these changes

2021-08-04 22:31 UTC, dlamkins requested changes
Changes look great!  Minor thing about the XML doc tag if you could either remove it or add one for each of the three calls there.  

If you just meant it as a more typical comment, we could probably just remove the XML portion of the tags and leave:

```cs
// Get state of modifier keys
```

2021-08-04 22:31 UTC, dlamkins commented on Blish HUD/Controls/TextInputBase.cs
> +        /// </summary>
Just FYI, this will only apply this summary to the `IsShiftDown`.  It won't apply it to the two below it.

2021-08-05 08:08 UTC, dlamkins approved these changes

2021-08-05 08:09 UTC, merged

2021-08-05 22:25 UTC, itsShoww commented
I'm very new to github and Blishhud too. I wasn't sure how to communicate with the people developing these modules (this is the only way I found) but I came across a post and a GIF about the Special Forces module (rotation addon) and I was wondering if it's already working/released, I've downloaded the "Blish hud modules master" zip folder and placed it on the modules folder but whenever I launch the game and blish, it says "you currently dont have any modules". I'd love to try this out, any help is appreciated, and sorry if this is totally the wrong way to contact you guys.

2021-08-06 07:57 UTC, greaka commented
Hey there!
This is indeed not the optimal place to ask such a question.
If you have trouble installing Blish-HUD or modules, visit https://blishhud.com/ for a guide.
If you still have questions after that, come and chat with us on our Discord server!
https://discord.gg/zhj23Sv5mA
If you don't have or want to use Discord, then open a new issue on this page please. You find issues at the top of this site.