Allow custom textbox background color
blish-hud/Blish-HUD pull request #591
Opened 2022-01-27 22:25 UTC by agaertner

Small tweak to hide the background of a multiline textbox in order to use a custom one or to have it react dynamically on focus change.
The simple textbox uses a texture and I wasn't sure if I should redo it to be drawn by a single pixel like in the multiline textbox. I could remove the texture and allow color customization here as well.

2022-01-27 22:28 UTC, dlamkins commented
Seems most intuitive / useful if we just have the option to hide the background.  Controls already have a background color, but if a custom background was needed it would probably be best to just throw the multiline textbox without a background into a container which draws what is needed.

2022-01-27 23:04 UTC, agaertner commented
Like so?

2022-01-28 18:46 UTC, dlamkins requested changes

2022-01-28 18:46 UTC, dlamkins commented on Blish HUD/Controls/MultilineTextBox.cs
> +            set {
Use `SetProperty` instead which automates all of this.

2022-01-28 18:46 UTC, dlamkins commented on Blish HUD/Controls/MultilineTextBox.cs
> +            if (!HideBackground) {
For consistency, let's do `this.HideBackground`.

2022-01-28 18:46 UTC, dlamkins commented on Blish HUD/Controls/Textbox.cs
> +            set {
Use `SetProperty` instead which automates all of this.

2022-01-28 18:46 UTC, dlamkins commented on Blish HUD/Controls/Textbox.cs
> +            if (!HideBackground) {
Same here, let's use `this.HideBackground`.

2022-01-28 18:46 UTC, dlamkins commented
Yeah, that's exactly what I meant.  🙂 Made a couple of notes for quick revisions that should only take a moment.  👍

2022-01-28 19:03 UTC, agaertner commented
> Yeah, that's exactly what I meant. 🙂 Made a couple of notes for quick revisions that should only take a moment. 👍

All done 👍

2022-01-28 19:05 UTC, dlamkins approved these changes

2022-01-28 19:06 UTC, dlamkins commented
Perfection.  Thanks!

2022-01-28 19:06 UTC, merged