User defined interact key
blish-hud/Blish-HUD pull request #597
Opened 2022-02-04 20:15 UTC by entrhopi

#582

New settings entry so users can set interact to the same keybind they use ingame.

2022-02-08 04:53 UTC, dlamkins commented
Once the above is addressed, we should be ready to merge.  🙂

2022-02-09 06:54 UTC, dlamkins requested changes

2022-02-09 06:54 UTC, dlamkins commented on Blish HUD/GameServices/OverlayService.cs
> +        public SettingEntry<KeyBinding> InteractKey { get; private set; }
I think eventually we'll want to rework where all of the settings for the keybinds so to avoid a breaking change down the line, could we make this an internal property for now?  😃

2022-02-09 14:47 UTC, dlamkins approved these changes

2022-02-09 14:47 UTC, merged

2022-02-10 00:04 UTC, jojorne commented
Can we use the mouse for binding?

2022-02-10 00:10 UTC, dlamkins commented
Only if it produces a key press event.  Similarly to the game itself, we don't support mouse button bindings.

2022-02-10 00:12 UTC, jojorne commented
Oh? Okay. It's just that my in-game action key is Mouse3.

2022-02-10 00:26 UTC, dlamkins commented
Ah, I see, the game does allow mouse buttons for binding.

In any case, though, the answer is that this is not currently supported in Blish HUD.  It would require some bifurcation of the input logic.

Most mice support rebinding the mouse buttons to standard key presses, so at this time that would be our only supported way you could use that button for interact.