GitHub Action Updates & Dependabot Implementation
blish-hud/Blish-HUD pull request #737
Opened 2022-08-31 06:15 UTC by BillChirico

- Update GitHub action versions
- Add dependabot package updates for `github-actions` and `nuget`
  - Added @dlamkins as auto assigner and reviewer for all of the automated PRs
  - Check for updates on a daily interval
  - **Note: Will need to create the labels assigned to the PRs, such as `dependencies`, `github-actions`, and `.NET` if you want them to be assigned to the PRs**

2022-08-31 21:38 UTC, dlamkins commented
Running it to see if there are any deviations from our standard builds with the new action versions.

2022-08-31 21:41 UTC, dlamkins requested changes

2022-08-31 21:41 UTC, dlamkins commented on .github/workflows/ci.yml
> +      - uses: microsoft/setup-msbuild@v1.1.1
> Error: Unable to resolve action `microsoft/setup-msbuild@v1.1.1`, unable to find version `v1.1.1`

2022-08-31 21:41 UTC, dlamkins commented on .github/workflows/pr.yml
> +      - uses: microsoft/setup-msbuild@v1.1.1
> Error: Unable to resolve action `microsoft/setup-msbuild@v1.1.1`, unable to find version `v1.1.1`

2022-08-31 21:41 UTC, dlamkins commented on .github/workflows/tag.yml
> +      - uses: microsoft/setup-msbuild@v1.1.1
> Error: Unable to resolve action `microsoft/setup-msbuild@v1.1.1`, unable to find version `v1.1.1`

2022-09-01 16:30 UTC, BillChirico commented on .github/workflows/ci.yml
> +      - uses: microsoft/setup-msbuild@v1.1.1
Fix version as per latest from https://github.com/marketplace/actions/setup-msbuild

2022-09-01 16:30 UTC, BillChirico commented on .github/workflows/tag.yml
> +      - uses: microsoft/setup-msbuild@v1.1.1
Fixed version as per latest from https://github.com/marketplace/actions/setup-msbuild

2022-09-01 16:31 UTC, BillChirico commented on .github/workflows/pr.yml
> +      - uses: microsoft/setup-msbuild@v1.1.1
Fixed version as per latest from https://github.com/marketplace/actions/setup-msbuild

2022-09-06 06:52 UTC, dlamkins approved these changes

2022-09-06 06:52 UTC, merged